name: mobile_speech_recognition
description: "Speech analysis Mobile Application"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  ffmpeg_kit_flutter_new: ^1.6.1
  path: ^1.8.3
  onnxruntime: ^1.4.1
  sqflite: ^2.4.2
  intl: ^0.19.0
  flutter_carousel_widget: ^3.1.0
  audio_waveforms: ^1.3.0
  provider: ^6.0.5
  http: ^1.3.0
  logger: ^2.0.2+1
  just_audio: ^0.10.3
  audio_video_progress_bar: ^2.0.3
  file_picker: ^8.1.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  package_info_plus: ^8.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  device_preview: ^1.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/splash_screen.png
  android: true
  ios: false

  android_12:
    image: assets/icon/splash_screen.png
    icon_background_color: "#FFFFFF"
    color: "#FFFFFF"
   
flutter:
  uses-material-design: true
  assets:
    - assets/models/
